SYNERGY-854 Compiling with MSVC 2014 causes error C2280 (#7099)
* SYNERGY-854 Compiling with MSVC 2014 causes error C2280
*Fix compilation error

* SYNERGY-854 Compiling with MSVC 2014 causes error C2280
*Update ChangeLog

* SYNERGY-854 Compiling with MSVC 2014 causes error C2280
*Fix Utils compilation

* SYNERGY-854 Fix code smell

Co-authored-by: Andrii Batyiev <andrii-external@symless.com>
Co-authored-by: SerhiiGadzhilov <71632867+SerhiiGadzhilov@users.noreply.github.com>
Co-authored-by: Serhii Hadzhilov <serhii-external@symless.com>